export type ActivityType =
  | "investment_created"
  | "investment_updated"
  | "investment_deleted"
  | "family_member_added"
  | "family_member_updated"
  | "family_member_deactivated"
  | "settings_updated"
  | "investment_type_added"
  | "investment_type_updated"
  | "investment_type_deactivated"
  | "dashboard_shared"
  | "liquid_asset_added"
  | "liquid_asset_updated"
  | "liquid_asset_deleted";