// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpawzvoawoyxnhllasfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwYXd6dm9hd295eG5obGxhc2Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQwODc5NjMsImV4cCI6MjA0OTY2Mzk2M30.7IytrUMqajDnZDgXP7pWqmJb66z8NCeAhDj0Jt-v0cs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);